language: node_js
node_js:
  - "18"

services:
  - docker

cache:
  directories:
    - backend/node_modules

before_install:
  - docker --version
  - node --version
  - npm --version

jobs:
  include:
    - name: "Backend - Pruebas Unitarias"
      script:
        - cd backend
        - npm ci
        - npm test -- --passWithNoTests --forceExit

    - name: "Docker - Build Images"
      script:
        - docker compose build

branches:
  only:
    - main
    - master

notifications:
  email:
    on_success: never
    on_failure: always
